name: 'build JMS replay uploader'
author: 'Eric Lee'
description: 'Build JMS replay uploader'
inputs:
  GOOS:
    description: build os
    required: true
outputs:
  filename:
    description: 'The filename'
    value: ${{ steps.build-go-main.outputs.filename }}
runs:
  using: "composite"
  steps:
    - run: echo "current dir" ${pwd}
      shell: bash
    - id: build-go-main
      run: |
        go build -o .
        tar -czvf replay_uploader_${{ runner.os }}.tar.gz replay_uploader*
        echo "::set-output name=filename::$(echo replay_uploader_${{ runner.os }}.tar.gz)"
        ls -al
      shell: bash