name: 'build JMS tool'
author: 'Eric Lee'
description: 'Build JMS tool'
inputs:
  GOOS:
    description: build os
    required: true
outputs:
  filename:
    description: 'The filename'
    value: ${{ steps.build-go-main.outputs.filename }}
runs:
  using: "composite"
  steps:
    - run: echo "current dir" ${pwd}
      shell: bash
    - id: build-go-main
      run: |
        go build -o .
        tar -czvf jms-upload_${{ runner.os }}.tar.gz jms-upload*
        echo "::set-output name=filename::$(echo jms-upload_${{ runner.os }}.tar.gz)"
        ls -al
      shell: bash